module.exports = {
    INVALID_LOGIN_OR_PASSWORD: 'INVALID_LOGIN_OR_PASSWORD',
    WRONG_LOGIN_OR_PASSWORD: 'WRONG_LOGIN_OR_PASSWORD',
    LOGIN_IS_ALREADY_EXIST: 'LOGIN_IS_ALREADY_EXIST',
    UNAUTHORIZED: 'UNAUTHORIZED'
};