module.exports = {
    INVALID_LOGIN_OR_PASSWORD: 'INVALID_LOGIN_OR_PASSWORD',
    WRONG_LOGIN_OR_PASSWORD: 'WRONG_LOGIN_OR_PASSWORD',
    LOGIN_ALREADY_EXISTS: 'LOGIN_ALREADY_EXISTS',
    UNAUTHORIZED: 'UNAUTHORIZED'
};